### ISSUE TITLE
Update for latest changes to oe-core

### ISSUE THREAD

**Issue by rossburton** [rust-embedded/meta-rust-bin#124]
oe-core now has Rust integrated, so there's eg `cargo.bbclass` in oe-core.

This layer should merge any improvements it has into oe-core, and remove the classes. Ideally, it would simply be a few recipes which provide the same contents as the source-based packages in oe-core, but from the binaries, so it's a drop-in replacement to improve build times.

**Comment by posborne** [comment]
With #136 we've introduced a rename to avoid conflicts.  There are still a few reasons that users may decide to use the rust impl from meta-rust-bin rather than meta-oe/meta-rust.  That's something we should probably seek to document better in this project.

Ones that I've heard/experienced include:
1. The build time to bootstrap the rust compiler as done by meta-oe/meta-rust is significant and can very negatively impact some organizations intended use.
2. For some, the prebuilt toolchains from the rust project itself might be preferred and more trusted than those that may be built from source as part of Yocto itself.
3. meta-oe for a given version is more-or-less fixed to a single version of the rust toolchain and it is non-trivial to introduce a different toolchain version without moving to a completely different yocto version.  With meta-rust-bin, this is not the case and it is generally quick (both in terms of developer and build time) to incorporate a new rust/cargo version set.  As an example, users on the Kirkstone LTS oe-core rust would be stuck on 1.59 which is unlikely to support many applications that are frequently shipping features that may want to depend on newer language features.
4. `meta-rust-bin` and `meta-rust`/`oe-core` approach dependencies for a rust crate differently.  `meta-rust-bin` doesn't require modeling of all the dependencies of a version of a crate within Yocto (e.g. via `cargo-bitbake`).  This has tradeoffs but for many projects the added Yocto work to model dependencies in this way may not be desirable.  This is definitely a case where `meta-rust-bin` is unable to take advantage of all the features of Yocto as a result (e.g. license tracking for rust-side dependencies or dynamic linking options for shared deps) but has other benefits.
