### ISSUE TITLE
QA warning on recipes that `inherit cargo_bin`

### ISSUE THREAD

**Issue by jin-eld** [rust-embedded/meta-rust-bin#183]
Hi,

I noticed that all of my recipes that use `cargo_bin` get the following warning (I'm on scarthgap, using meta-rust-bin `master:3a1bc43f32e6cb394b9916be681342a81be10a7c`):

```
WARNING: trippy-0.10.0-r0 do_package_qa: QA Issue: File /usr/bin/.debug/trip in package trippy-dbg contains reference to TMPDIR [buildpaths]
WARNING: trippy-0.10.0-r0 do_package_qa: QA Issue: File /usr/bin/trip in package trippy contains reference to TMPDIR [buildpaths]
WARNING: trippy-0.10.0-r0 do_package_qa: QA Issue: File /usr/lib/libtrippy.rlib in package trippy-dev contains reference to TMPDIR [buildpaths]
```

Since there is not really much that I do in the recipe itself, I assume that this is cause by something that happens behind the scenes in the bbclass, here's the recipe (`trippy_0.10.0.bb`):

```
DESCRIPTION = "trippy"
  
LICENSE  = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=22a53954e4e0ec258dfce4391e905dac"

SRC_URI = "git://github.com/fujiapple852/trippy;protocol=https;branch=master"

SRCREV = "14575e3fe03c07dfe7589bff7abae66d6e5df228"

S = "${WORKDIR}/git"

inherit cargo_bin

do_compile[network] = "1"
```

I know that the warning can be force-silenced, but is there perhaps a clean fix for this or am I missing something?

**Comment by frosch01** [comment]
Hi,

even that I am not part of this project, I may help with some information.

The warning comes from a yocto lint check (Insane). The idea is that paths which are typically strings in the executable are used which are only valid on the build platform. After a crossbuild things are running on a different file system, so paths be invalid on the target. So a valid and useful check. 

This is basically the same as running this command on the executable:

```
strings <executable> | grep /tmp/
````

Independent from if you are perhaps using such bad paths, Rust adds paths of source files as you use panic! macro. This macro is part of stdlib, so it is hard to replace. There [is this RFC](https://rust-lang.github.io/rfcs/3127-trim-paths.html) which is also implemented but did not stabilize es of now.

So, unfortunately nothing that could be fixed by this project.
