### ISSUE TITLE
Incorrect linker-wrapper used when target architecture is the same as build one

### ISSUE THREAD

**Issue by macpijan** [rust-embedded/meta-rust-bin#70]
When MACHINE is x86-64, `linker-native-wrapper.sh` is used instead of the `linker-wrapper.sh`. It causes the build to fail as the `ld` cannot find the target libraries (it is looking among the host libraries).
Forcing it to use the `linker-wrapper.sh` caused the build to pass. I think the problem is in this area: https://github.com/rust-embedded/meta-rust-bin/blob/master/classes/cargo.bbclass#L53

I would be glad to help fixing that if you have some advice.
I'm proficient in Yocto, but not so much with rust.

**Comment by nastevens** [comment]
Thanks @macpijan. The problem is that it's not currently possible (that I know of) to tell Rust to use one set of flags for compiling for the "host" and one set of flags for compiling for the "target" when the architectures are the same. We do need to compile host binaries as well because so many projects utilize a `build.rs`.

I don't have any immediate ideas to help unfortunately. I'll try to dig into this when I get some time.
